# -*- coding: utf-8 -*-
"""Stock_forecastingV1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11m-DQrXnCbqXMTiD2OCa2dumACbsMX_W

IMPORTING LIBRARIES
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

"""DOWNLOAD STOCK DATA"""

stock = "RELIANCE.NS"

data = yf.download(
    stock,
    start="2018-01-01",
    end="2024-01-01"
)

print(data.shape)
data.head()

"""DATA VISUALIZATION"""

plt.figure(figsize=(12,5))

plt.plot(data['Close'])

plt.title("Reliance Closing Price")
plt.xlabel("Date")
plt.ylabel("Price")

plt.show()

"""FEATURE ENGINEERING"""

data['MA20'] = data['Close'].rolling(window=20).mean()

data['MA50'] = data['Close'].rolling(window=50).mean()

delta = data['Close'].diff()

gain = delta.clip(lower=0)
loss = -delta.clip(upper=0)

avg_gain = gain.rolling(14).mean()
avg_loss = loss.rolling(14).mean()

rs = avg_gain / avg_loss

data['RSI'] = 100 - (100 / (1 + rs))

data = data.dropna()

print(data.shape)

features = data[
[
'Close',
'MA20',
'MA50',
'RSI',
'Volume'
]
]

print(features.shape)
features.head()

"""FEATURE SCALING"""

from sklearn.preprocessing import MinMaxScaler

feature_scaler = MinMaxScaler()
target_scaler = MinMaxScaler()

scaled_features = feature_scaler.fit_transform(features)

scaled_close = target_scaler.fit_transform(
    data[['Close']]
)

print(len(scaled_features))
print(len(scaled_close))

"""SLIDING WINDOW"""

window_size = 30

X = []
y = []

for i in range(window_size, len(scaled_features)):

    X.append(
        scaled_features[i-window_size:i]
    )

    y.append(
        scaled_close[i]
    )

X = np.array(X)
y = np.array(y)

print(X.shape)
print(y.shape)

"""TRAIN/TEST SPLIT"""

train_size = int(len(X) * 0.8)

X_train = X[:train_size]
X_test = X[train_size:]

y_train = y[:train_size]
y_test = y[train_size:]

print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

"""BASELINE MODEL"""

baseline_predictions = []

for sample in X_test:

    last_price = sample[-1][0]

    baseline_predictions.append(last_price)

baseline_predictions = np.array(
    baseline_predictions
)

baseline_predictions = baseline_predictions.reshape(-1,1)

baseline_predictions_actual = target_scaler.inverse_transform(
    baseline_predictions
)

y_test_actual = target_scaler.inverse_transform(
    y_test
)

print(baseline_predictions_actual.shape)
print(y_test_actual.shape)

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

mae = mean_absolute_error(
    y_test_actual,
    baseline_predictions_actual
)

rmse = np.sqrt(
    mean_squared_error(
        y_test_actual,
        baseline_predictions_actual
    )
)

print("BASELINE MAE:", mae)
print("BASELINE RMSE:", rmse)

plt.figure(figsize=(12,6))

plt.plot(
    y_test_actual,
    label="Actual Price"
)

plt.plot(
    baseline_predictions_actual,
    label="Baseline Prediction"
)

plt.legend()

plt.show()

"""LINEAR REGRESSION"""

X_train_lr = X_train.reshape(
    X_train.shape[0],
    -1
)

X_test_lr = X_test.reshape(
    X_test.shape[0],
    -1
)

from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()

lr_model.fit(
    X_train_lr,
    y_train
)

lr_predictions = lr_model.predict(
    X_test_lr
)

lr_predictions_actual = target_scaler.inverse_transform(
    lr_predictions
)

mae = mean_absolute_error(
    y_test_actual,
    lr_predictions_actual
)

rmse = np.sqrt(
    mean_squared_error(
        y_test_actual,
        lr_predictions_actual
    )
)

print("Linear Regression MAE:", mae)
print("Linear Regression RMSE:", rmse)

plt.figure(figsize=(12,6))

plt.plot(
    y_test_actual,
    label="Actual Price"
)

plt.plot(
    lr_predictions_actual,
    label="Linear Regression Prediction"
)

plt.title("Linear Regression Forecast")

plt.xlabel("Time")

plt.ylabel("Stock Price")

plt.legend()

plt.show()

"""LSTM"""

import tensorflow as tf

print(tf.__version__)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

model = Sequential()

model.add(
    LSTM(
        64,
        return_sequences=True,
        input_shape=(30,5)
    )
)

model.add(
    Dropout(0.2)
)

model.add(
    LSTM(64)
)

model.add(
    Dropout(0.2)
)

model.add(
    Dense(1)
)

model.compile(
    optimizer='adam',
    loss='mean_squared_error'
)

model.summary()

history = model.fit(
    X_train,
    y_train,
    epochs=60,
    batch_size=32,
    validation_split=0.1
)

lstm_predictions = model.predict(
    X_test
)

lstm_predictions_actual = target_scaler.inverse_transform(
    lstm_predictions
)

mae = mean_absolute_error(
    y_test_actual,
    lstm_predictions_actual
)

rmse = np.sqrt(
    mean_squared_error(
        y_test_actual,
        lstm_predictions_actual
    )
)

print("LSTM MAE:", mae)
print("LSTM RMSE:", rmse)

plt.figure(figsize=(12,6))

plt.plot(
    y_test_actual,
    label="Actual"
)

plt.plot(
    lstm_predictions_actual,
    label="LSTM"
)

plt.legend()

plt.show()

plt.plot(history.history['loss'])

plt.plot(history.history['val_loss'])

plt.legend(
    ['Train','Validation']
)

plt.show()

model.save("stock_lstm_model_v1.h5")

from google.colab import files
files.download("stock_lstm_model_v1.h5")

model.save("stock_lstm_model.keras")

from google.colab import files
files.download("stock_lstm_model.keras")

import joblib

joblib.dump(lr_model, "linear_regression_model.pkl")

from google.colab import files
files.download("linear_regression_model.pkl")